language: java

matrix:
  include:
    - dist: trusty
      jdk: oraclejdk8
    - dist: xenial
      jdk: openjdk11
    - dist: xenial
      jdk: openjdk12

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
